package com.wayfarer.immersivemaps.client;

import com.wayfarer.immersivemaps.config.ImmersiveMapsConfig;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.ColorControllerBuilder;
import dev.isxander.yacl3.api.controller.EnumControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.awt.*;

public class ImmersiveMapsConfigScreen {

    public static Screen create(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("config.immersivemaps.title"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.immersivemaps.category.client"))
                        .option(Option.<ImmersiveMapsConfig.WaypointDisplayType>createBuilder()
                                .name(Component.translatable("config.immersivemaps.waypointDisplayType"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.waypointDisplayType.description")))
                                .binding(ImmersiveMapsConfig.WaypointDisplayType.STANDARD, () -> ImmersiveMapsConfig.waypointDisplayType, val -> ImmersiveMapsConfig.waypointDisplayType = val)
                                .controller(opt -> EnumControllerBuilder.create(opt)
                                        .enumClass(ImmersiveMapsConfig.WaypointDisplayType.class))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.immersivemaps.showLocatorMarkers"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.showLocatorMarkers.description")))
                                .binding(true, () -> ImmersiveMapsConfig.showLocatorMarkers, val -> ImmersiveMapsConfig.showLocatorMarkers = val)
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.compassWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.compassWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.compassWaypointColor), val -> ImmersiveMapsConfig.compassWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.recoveryCompassWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.recoveryCompassWaypointColor.description")))
                                .binding(new Color(0x888888), () -> new Color(ImmersiveMapsConfig.recoveryCompassWaypointColor), val -> ImmersiveMapsConfig.recoveryCompassWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.immersivemaps.category.structures"))
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.villageWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.villageWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.villageWaypointColor), val -> ImmersiveMapsConfig.villageWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.templeWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.templeWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.templeWaypointColor), val -> ImmersiveMapsConfig.templeWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.monumentWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.monumentWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.monumentWaypointColor), val -> ImmersiveMapsConfig.monumentWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.mansionWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.mansionWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.mansionWaypointColor), val -> ImmersiveMapsConfig.mansionWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.trialChambersWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.trialChambersWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.trialChambersWaypointColor), val -> ImmersiveMapsConfig.trialChambersWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.buriedTreasureWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.buriedTreasureWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.buriedTreasureWaypointColor), val -> ImmersiveMapsConfig.buriedTreasureWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.immersivemaps.swampHutWaypointColor"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.swampHutWaypointColor.description")))
                                .binding(new Color(0xFFFFFF), () -> new Color(ImmersiveMapsConfig.swampHutWaypointColor), val -> ImmersiveMapsConfig.swampHutWaypointColor = val.getRGB() & 0xFFFFFF)
                                .controller(ColorControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.immersivemaps.category.server"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.immersivemaps.sendStructureWaypoints"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.sendStructureWaypoints.description")))
                                .binding(true, () -> ImmersiveMapsConfig.sendStructureWaypoints, val -> ImmersiveMapsConfig.sendStructureWaypoints = val)
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.immersivemaps.sendBannerWaypoints"))
                                .description(OptionDescription.of(Component.translatable("config.immersivemaps.sendBannerWaypoints.description")))
                                .binding(true, () -> ImmersiveMapsConfig.sendBannerWaypoints, val -> ImmersiveMapsConfig.sendBannerWaypoints = val)
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .build())
                .save(ImmersiveMapsConfig::save)
                .build()
                .generateScreen(parent);
    }
}
